# 🧠 Natural Language Processing (NLP)

## 📌 What is NLP?

**NLP (Natural Language Processing)** is a branch of **Artificial Intelligence (AI)** that helps computers understand, process, analyze, and generate **human language**.

## 🎯 Main Goals of NLP

- Understand human language
- Process and analyze text
- Extract useful information
- Understand sentiment and emotions
- Translate between languages
- Generate human-like text

## 🔧 Applications of NLP

- 🤖 Chatbots
- 🌐 Machine Translation
- 😊 Sentiment Analysis
- 📧 Spam Detection
- 🔍 Search Engines
- 📝 Text Summarization
- 🎙️ Speech Recognition
- ❓ Question Answering

## 🔄 Basic NLP Pipeline

Raw Text  
↓  
Text Cleaning  
↓  
Tokenization  
↓  
Stopword Removal  
↓  
Stemming / Lemmatization  
↓  
Feature Extraction  
↓  
Machine Learning / Deep Learning  
↓  
Prediction / Output

## 💡 Example

**Input:**
> "I really love this movie!"

**NLP Task:** Sentiment Analysis

**Output:**
> Positive 😊

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [3]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
df['emotion'].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [6]:
unique_emotion = df['emotion'].unique()

emotion_numbers = {}
i = 0 

for emo in unique_emotion:
    emotion_numbers[emo] = i 
    i+=1 

df['emotion'] = df['emotion'].map(emotion_numbers)

In [7]:
emotion_numbers

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [8]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [9]:
df['text']  = df['text'].apply(lambda x: x.lower())

In [10]:
df.sample(5)

                                                    text  emotion
15580  i feel so delighted when the varsities picked ...        5
7620   i remember feeling impatient with her and even...        1
1218   i was using it to vent out ugly feelings and b...        1
14523  i describe this it is so wonderful i can close...        5
12827               i have been feeling quite productive        5

In [11]:
import string 

def remove_punc(txt): 
    return txt.translate(str.maketrans('','',string.punctuation))

In [12]:
df['text'] = df['text'].apply(remove_punc)

In [13]:
df.sample(5)

                                                    text  emotion
10966  i feel like you are more into self promotion t...        2
7960   i am looking forward to a great year in i am f...        5
2571                 i feel nervous just walking outside        4
3426   i would feel so devastated that every channel ...        0
1684   i see myself starting to feel the emotional de...        0

In [14]:
def remove_numbers(txt): 
    new = ''
    for i in txt: 
        if not i.isdigit(): 
            new = new + i 
    return new

In [15]:
df['text']  = df['text'].apply(remove_numbers)

In [16]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [17]:
def remove_emojis(txt): 
    new = ''
    for i in txt: 
        if  i.isascii(): 
            new = new + i 
    return new

In [18]:
df['text']  = df['text'].apply(remove_emojis)

In [19]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [20]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [21]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\MUSTAK\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\MUSTAK\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\MUSTAK\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
stop_words = set(stopwords.words('english'))

In [23]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [24]:
len(stop_words)

198

In [25]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [26]:
def remove_stop_words(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if i not in stop_words: 
            cleaned.append(i)
    return ' '.join(cleaned)

In [27]:
remove_stop_words(df.loc[1]['text'])

'go feeling hopeless damned hopeful around someone cares awake'

In [28]:
df['text'] = df['text'].apply(remove_stop_words)

In [29]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

document = df['text'].tolist()

vectorizer = CountVectorizer(max_features=1000)
x = vectorizer.fit_transform(document)

In [31]:
print("Vocabulary: ",vectorizer.get_feature_names_out())
print('Bow Matrix: \n',x.toarray())

Vocabulary:  ['ability' 'able' 'absolutely' 'abused' 'acceptable' 'accepted' 'aching'
 'across' 'act' 'actually' 'add' 'admit' 'adventurous' 'afraid' 'age'
 'agitated' 'ago' 'ahead' 'air' 'allow' 'allowed' 'almost' 'alone' 'along'
 'already' 'also' 'although' 'always' 'amazed' 'amazing' 'amount' 'amp'
 'amused' 'anger' 'angry' 'annoyed' 'another' 'answer' 'anxiety' 'anxious'
 'anymore' 'anyone' 'anything' 'anyway' 'appreciative' 'apprehensive'
 'arms' 'around' 'art' 'artistic' 'ashamed' 'ask' 'asked' 'asking'
 'assured' 'attention' 'away' 'awful' 'awkward' 'baby' 'back' 'bad'
 'beaten' 'beautiful' 'become' 'bed' 'began' 'begin' 'beginning' 'behind'
 'believe' 'beloved' 'best' 'better' 'beyond' 'big' 'bit' 'bitchy'
 'bitter' 'black' 'blank' 'blessed' 'blog' 'blogging' 'body' 'book'
 'books' 'boring' 'bothered' 'boy' 'boyfriend' 'brain' 'brave' 'break'
 'breath' 'bring' 'broke' 'burdened' 'busy' 'buy' 'call' 'called' 'calm'
 'came' 'cant' 'car' 'care' 'career' 'carefree' 'caring' 'case' 'casual'
 'cause' 'certain' 'certainly' 'chance' 'change' 'characters' 'chest'
 'child' 'children' 'choice' 'christmas' 'church' 'class' 'clever' 'close'
 'cold' 'college' 'come' 'comes' 'comfortable' 'coming' 'comments'
 'community' 'company' 'complacent' 'complete' 'completely' 'computer'
 'confident' 'confused' 'connection' 'consider' 'constantly' 'content'
 'contented' 'continue' 'control' 'conversation' 'convinced' 'cool'
 'could' 'couldnt' 'country' 'couple' 'course' 'cranky' 'crap' 'crappy'
 'crazy' 'create' 'creative' 'cry' 'crying' 'curious' 'cut' 'cute' 'dad'
 'damaged' 'damn' 'dangerous' 'dark' 'day' 'days' 'dazed' 'deal' 'death'
 'decide' 'decided' 'decision' 'deep' 'deeply' 'defeated' 'definitely'
 'delicate' 'delicious' 'delighted' 'depressed' 'deprived' 'describe'
 'desire' 'despite' 'determined' 'devastated' 'didnt' 'die' 'different'
 'dirty' 'disappointed' 'discontent' 'discouraged' 'disgusted'
 'disheartened' 'disillusioned' 'dissatisfied' 'distracted' 'distraught'
 'distressed' 'disturbed' 'divine' 'doesnt' 'done' 'dont' 'doomed' 'door'
 'doubt' 'doubtful' 'drained' 'dream' 'drink' 'due' 'dull' 'dumb' 'eager'
 'early' 'easy' 'eat' 'eating' 'ecstatic' 'effort' 'either' 'else'
 'embarrassed' 'emotional' 'emotionally' 'emotions' 'empty' 'end' 'ended'
 'energetic' 'energy' 'enjoy' 'enjoyed' 'enough' 'entire' 'entirely'
 'envious' 'especially' 'etc' 'even' 'evening' 'ever' 'every' 'everyday'
 'everyone' 'everything' 'exactly' 'except' 'excited' 'exhausted' 'expect'
 'expected' 'experience' 'explain' 'express' 'extra' 'extremely' 'eyes'
 'fabulous' 'face' 'fact' 'fairly' 'faithful' 'fake' 'fall' 'family'
 'fantastic' 'far' 'father' 'fear' 'fearful' 'feel' 'feeling' 'feelings'
 'feels' 'felt' 'festive' 'film' 'finally' 'find' 'finding' 'fine'
 'finish' 'finished' 'first' 'fit' 'five' 'focus' 'fond' 'food' 'foolish'
 'forget' 'forward' 'found' 'four' 'frantic' 'free' 'friend' 'friendly'
 'friends' 'frightened' 'front' 'frustrated' 'fuck' 'fucked' 'fucking'
 'full' 'fully' 'fun' 'funny' 'future' 'game' 'gave' 'general' 'generally'
 'generous' 'gentle' 'get' 'gets' 'getting' 'gift' 'girl' 'girls' 'give'
 'given' 'giving' 'glad' 'glamorous' 'gloomy' 'go' 'god' 'goes' 'going'
 'gon' 'gone' 'good' 'gorgeous' 'got' 'gotten' 'grateful' 'great' 'greedy'
 'groggy' 'grouchy' 'ground' 'group' 'grumpy' 'guess' 'guilt' 'guilty'
 'guy' 'guys' 'hair' 'half' 'hand' 'hands' 'happen' 'happened' 'happening'
 'happens' 'happiness' 'happy' 'hard' 'hate' 'hated' 'hateful' 'havent'
 'head' 'health' 'healthy' 'hear' 'heard' 'heart' 'heartbroken' 'hell'
 'help' 'helping' 'helpless' 'hes' 'hesitant' 'high' 'hit' 'hold' 'home'
 'homesick' 'honest' 'honestly' 'honored' 'honoured' 'hope' 'hopeful'
 'hopeless' 'horny' 'horrible' 'hostile' 'hot' 'hour' 'hours' 'house'
 'however' 'href' 'http' 'huge' 'human' 'humiliated' 'hurt' 'husband' 'id'
 'idea' 'idiotic' 'ignored' 'ill' 'im' 'imagine' 'img' 'impatient'
 'important' 'impressed' 'inadequate' 'incredibly' 'indecisive'
 'inhibited' 'innocent' 'insecure' 'inside' 'inspired' 'instead'
 'insulted' 'intelligent' 'intimidated' 'invigorated' 'irritable'
 'irritated' 'isnt' 'isolated' 'issue' 'issues' 'ive' 'jaded' 'jealous'
 'job' 'joy' 'joyful' 'keen' 'keep' 'keeping' 'kept' 'kid' 'kids' 'kind'
 'kinda' 'knew' 'know' 'knowing' 'knowledge' 'known' 'lack' 'lame' 'last'
 'late' 'lately' 'later' 'lazy' 'learn' 'learned' 'learning' 'least'
 'leave' 'leaving' 'left' 'less' 'let' 'lethargic' 'letting' 'level' 'lie'
 'life' 'light' 'like' 'liked' 'line' 'list' 'listen' 'listening'
 'listless' 'little' 'live' 'lives' 'living' 'lol' 'lonely' 'long'
 'longer' 'longing' 'look' 'looked' 'looking' 'looks' 'lose' 'losing'
 'loss' 'lost' 'lot' 'lots' 'lousy' 'love' 'loved' 'lovely' 'loving' 'low'
 'loyal' 'lucky' 'mad' 'made' 'make' 'makes' 'making' 'man' 'managed'
 'many' 'matter' 'may' 'maybe' 'mean' 'means' 'meet' 'meeting'
 'melancholy' 'mellow' 'memories' 'men' 'mention' 'messy' 'met' 'might'
 'mind' 'mine' 'minutes' 'miserable' 'miss' 'missed' 'missing' 'mom'
 'moment' 'moments' 'money' 'month' 'months' 'mood' 'morning' 'mostly'
 'mother' 'move' 'movie' 'moving' 'much' 'music' 'must' 'na' 'name'
 'naughty' 'need' 'needed' 'needs' 'needy' 'negative' 'nervous' 'never'
 'new' 'news' 'next' 'nice' 'night' 'normal' 'nostalgic' 'nothing' 'numb'
 'number' 'offended' 'often' 'oh' 'ok' 'old' 'one' 'ones' 'onto' 'open'
 'opportunity' 'optimistic' 'order' 'others' 'outside' 'overwhelmed'
 'pain' 'paper' 'paranoid' 'parents' 'part' 'particularly' 'party'
 'passed' 'passionate' 'past' 'pathetic' 'pay' 'peace' 'peaceful' 'people'
 'perfect' 'perhaps' 'person' 'personal' 'personally' 'petty' 'phone'
 'photos' 'physical' 'physically' 'pick' 'picture' 'piece' 'pissed'
 'place' 'plan' 'play' 'playful' 'playing' 'pleasant' 'please' 'pleased'
 'point' 'popular' 'positive' 'possible' 'possibly' 'post' 'posting'
 'precious' 'pregnant' 'presence' 'pressure' 'pressured' 'pretty'
 'privileged' 'probably' 'problems' 'productive' 'project' 'proud'
 'punished' 'push' 'put' 'putting' 'questions' 'quickly' 'quite' 'race'
 'rather' 'reach' 'read' 'readers' 'reading' 'ready' 'real' 'realize'
 'realized' 'really' 'reason' 'reasons' 'reassured' 'rebellious'
 'recently' 'red' 'regretful' 'rejected' 'relationship' 'relaxed'
 'relieved' 'reluctant' 'remember' 'remorseful' 'resentful' 'resolved'
 'respect' 'respected' 'rest' 'restless' 'results' 'rich' 'right'
 'romantic' 'room' 'rotten' 'rude' 'run' 'running' 'rushed' 'sad'
 'sadness' 'safe' 'said' 'sat' 'satisfied' 'saw' 'say' 'saying' 'says'
 'scared' 'school' 'season' 'second' 'see' 'seeing' 'seem' 'seems' 'seen'
 'self' 'selfish' 'sense' 'sentimental' 'seriously' 'set' 'several' 'sex'
 'shaken' 'shaky' 'share' 'sharing' 'shes' 'shit' 'shitty' 'shocked'
 'short' 'shouldnt' 'show' 'shy' 'sick' 'side' 'simple' 'simply' 'since'
 'sincere' 'single' 'sister' 'sit' 'sitting' 'situation' 'skeptical'
 'skin' 'sleep' 'sleeping' 'slightly' 'small' 'smart' 'smile' 'smug'
 'social' 'somehow' 'someone' 'something' 'sometimes' 'somewhat'
 'somewhere' 'son' 'song' 'songs' 'soon' 'sorry' 'sort' 'soul' 'sound'
 'space' 'speak' 'special' 'spend' 'spending' 'spent' 'spirit' 'src'
 'stand' 'start' 'started' 'starting' 'state' 'stay' 'step' 'still'
 'stomach' 'stop' 'stopped' 'stories' 'story' 'strange' 'strength'
 'stress' 'stressed' 'strong' 'strongly' 'stubborn' 'students' 'stuff'
 'stupid' 'style' 'submissive' 'successful' 'suddenly' 'suffering'
 'summer' 'sun' 'super' 'superior' 'support' 'supporting' 'supportive'
 'suppose' 'supposed' 'sure' 'surprised' 'suspicious' 'sweet'
 'sympathetic' 'take' 'taken' 'taking' 'talented' 'talk' 'talking' 'team'
 'tears' 'tell' 'telling' 'tend' 'tender' 'terrible' 'terribly' 'terrific'
 'terrified' 'thank' 'thankful' 'thats' 'theres' 'theyre' 'thing' 'things'
 'think' 'thinking' 'though' 'thought' 'thoughts' 'threatened' 'three'
 'thrilled' 'throw' 'time' 'times' 'tired' 'title' 'today' 'together'
 'told' 'tomorrow' 'tonight' 'took' 'top' 'tortured' 'totally' 'touch'
 'toward' 'towards' 'tragic' 'training' 'tried' 'trip' 'triumphant'
 'troubled' 'true' 'truly' 'trust' 'trusting' 'truth' 'try' 'trying'
 'turn' 'two' 'type' 'ugly' 'uncertain' 'uncomfortable' 'understand'
 'unfortunate' 'ungrateful' 'unhappy' 'unimportant' 'unloved' 'unpleasant'
 'unsure' 'unwelcome' 'upon' 'upset' 'us' 'use' 'used' 'useful' 'useless'
 'using' 'usual' 'usually' 'utterly' 'vain' 'valuable' 'valued' 'violent'
 'virtuous' 'vital' 'voice' 'vulnerable' 'wait' 'waiting' 'wake' 'walk'
 'walked' 'walking' 'wan' 'want' 'wanted' 'wanting' 'wants' 'warm' 'wasnt'
 'watch' 'watching' 'water' 'way' 'ways' 'wear' 'wearing' 'weather' 'week'
 'weekend' 'weeks' 'weepy' 'weight' 'weird' 'welcomed' 'well' 'went'
 'whatever' 'whats' 'whenever' 'whether' 'whole' 'wish' 'within' 'without'
 'woke' 'woman' 'women' 'wonder' 'wonderful' 'wondering' 'wont' 'word'
 'words' 'work' 'worked' 'working' 'world' 'worried' 'worry' 'worse'
 'worth' 'worthless' 'worthwhile' 'would' 'wouldnt' 'write' 'writing'
 'written' 'wrong' 'wronged' 'wrote' 'www' 'year' 'years' 'yes'
 'yesterday' 'yet' 'young' 'youre']
Bow Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [32]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [34]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test = train_test_split(df['text'],
                                                 df['emotion'],
                                                 test_size=0.21,
                                                 random_state=42)

In [38]:
x_train

3481                  feel depressed moody lethargic tired
4333                            feel especially passionate
10776    feel though class still useful end owning busi...
14817    really shut lot end pregnancy feeling even irr...
12958    probably written closer thanksgiving busy fran...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12640, dtype: object

In [39]:
x_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
1602     spent day day feeling morose every awhile woul...
321      feel convinced plus many diverse price tags fe...
4630     wish comforting feeling instead feels strange ...
13044    feel amazed watch victim intensely lying blond...
11126    know effects day day happenings serenity subtl...
Name: text, Length: 3360, dtype: object

In [40]:
print("X_train:", x_train.shape)
print("X_test:", x_test.shape)
print("Y_train:", y_train.shape)
print("Y_test:", y_test.shape)

X_train: (12640,)
X_test: (3360,)
Y_train: (12640,)
Y_test: (3360,)

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

from sklearn.naive_bayes import MultinomialNB 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score

In [80]:
# CountVectorizer with MultinomialNB
bow_vectorizer = CountVectorizer()

x_train_bow = bow_vectorizer.fit_transform(x_train)
x_test_bow = bow_vectorizer.transform(x_test)

nb_model = MultinomialNB() 
nb_model.fit(x_train_bow,y_train) 

pred_nb = nb_model.predict(x_test_bow) 
print(accuracy_score(y_test,pred_nb))

0.7666666666666667

In [81]:
# TfidfVectorizer with MultinomialNB
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,1))

x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

nb_model = MultinomialNB() 
nb_model.fit(x_train_tfidf,y_train) 

pred_nb = nb_model.predict(x_test_tfidf) 
print(accuracy_score(y_test,pred_nb))

0.6610119047619047

In [85]:
# CountVectorizer with LogisticRegression
bow_vectorizer = CountVectorizer()

x_train_bow = bow_vectorizer.fit_transform(x_train)
x_test_bow = bow_vectorizer.transform(x_test)

lgr_model = LogisticRegression() 
lgr_model.fit(x_train_bow,y_train) 


pred_lgr = lgr_model.predict(x_test_bow) 
print(accuracy_score(y_test,pred_lgr))

0.8892857142857142

In [86]:
# TfidfVectorizer with LogisticRegression
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,1))

x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

lgr_model = LogisticRegression() 
lgr_model.fit(x_train_tfidf,y_train) 

pred_lgr = lgr_model.predict(x_test_tfidf) 
print(accuracy_score(y_test,pred_lgr))

0.8589285714285714

In [87]:
# CountVectorizer with LinearSVC
bow_vectorizer = CountVectorizer()

x_train_bow = bow_vectorizer.fit_transform(x_train)
x_test_bow = bow_vectorizer.transform(x_test)

svc_model = LinearSVC() 
svc_model.fit(x_train_bow,y_train) 

pred_svc = svc_model.predict(x_test_bow) 
print(accuracy_score(y_test,pred_svc))

0.8886904761904761

In [88]:
# TfidfVectorizer with LinearSVC
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,1))

x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

svc_model = LinearSVC() 
svc_model.fit(x_train_tfidf,y_train) 

pred_svc = svc_model.predict(x_test_tfidf) 
print(accuracy_score(y_test,pred_svc))

0.8901785714285714

In [90]:
# Save model and vectorizer
import joblib

joblib.dump(tfidf_vectorizer,'tfidf_vectorizer.pkl')
joblib.dump(svc_model,'svm_model.pkl')

print("Model saved successfully!")

Model saved successfully!